---
- hosts: localhost
  vars_files:
    - ['settings.yml', 'defaults/settings.yml.default']
    - ['~/cloudbox/accounts.yml', '~/cloudbox/defaults/accounts.yml.default']
    - ['~/cloudbox/settings.yml', '~/cloudbox/defaults/settings.yml.default']
    - ['~/cloudbox/adv_settings.yml', '~/cloudbox/defaults/adv_settings.yml.default']
  roles:
    - { role: settings, tags: ['always', 'settings'] }
    - { role: pre_tasks, tags: ['pre_tasks']}
    - { role: kanboard, tags: ['kanboard'] }
    - { role: audioserve, tags: ['audioserve'] }
    - { role: wekan, tags: ['wekan'] }
    - { role: unifi, tags: ['unifi'] }
    - { role: archiveteam, tags: ['archiveteam'] }
    - { role: asshama, tags: ['asshama'] }
    - { role: epms, tags: ['epms'] }
    - { role: docuwiki, tags: ['docuwiki'] }
    - { role: delugevpn, tags: ['delugevpn'] }
    - { role: flexget, tags: ['flexget'] }
    - { role: shokoserver, tags: ['shokoserver'] }
    - { role: nefarious, tags: ['nefarious'] }
    - { role: sshwifty, tags: ['sshwifty'] }
    - { role: channelsdvr, tags: ['channelsdvr'] }
    - { role: wetty, tags: ['wetty'] }
    - { role: mkvtoolnix, tags: ['mkvtoolnix'] }
    - { role: embystats, tags: ['embystats'] }
    - { role: calibreweb, tags: ['calibreweb'] }
