---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: wekan
  when: cloudflare_enabled

- name: Stop and remove any existing containers
  docker_container:
  with_items:
    - wekandb
    - wekan
  state: absent

- name: Create required directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/wekan
    - /opt/wekan/wekandb
    - /opt/wekan/wekandbdump

- name: mongo wekanDB Role
  docker_container:
    name: wekandb
    image: mongo:3.2.21
    restart: always
    command: mongod --smallfiles --oplogSize 128
    networks:
      - name: cloudbox
        aliases:
          - mongodb
    expose:
      - 27017
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/wekan/wekandb:/data/db"
      - "/opt/wekan/wekandbdump:/dump"

- name: "sleep for 120 seconds and continue"
  wait_for: timeout=120

- name: Create and start wekan container
  docker_container:
    name: wekan
    image: "quay.io/wekan/wekan:master"
    pull: yes

    env:
      MONGO_URL: mongodb://wekandb:27017/wekan
      ROOT_URL: https://wekan.{{ user.domain }}
      #MAIL_URL: 'smtp://<mail_url>:25/?ignoreTLS=true&tls={rejectUnauthorized:false}'
      #MAIL_FROM: 'Wekan Notifications <noreply.wekan@mydomain.com>'
      WITH_API: true
      BROWSER_POLICY_ENABLED: true
      VIRTUAL_HOST: "wekan.{{ user.domain }}"
      VIRTUAL_PORT: 443
      VIRTUAL_PROTO: https
      LETSENCRYPT_HOST: "wekan.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
      HTTPS_METHOD: noredirect

    depends_on:
      - wekandb

    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/wekan/wekandb:/data/db"
      - "/opt/wekan/wekandbdump:/dump"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - wekan
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
