---
- name: Install required packages
  apt: "name={{ item }} state=latest"
  with_items:
    - python-pymysql

- name: MariaDB Role
  include_role:
    name: mariadb

- name: "sleep for 120 seconds and continue"
  wait_for: timeout=120

- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: kanboard
  when: cloudflare_enabled

- name: Stop and remove any existing containers
  docker_container: "name={{ item }} state=absent"
  with_items:
    - kanboard

- name: Create kanboard database
  mysql_db:
    name: kanboardapp
    login_user: root
    login_password: password321
    state: present

- name: Create required directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/kanboard
    - /opt/kanboard/data
    - /opt/kanboard/plugins

- name: Create and start kanboard container
  docker_container:
    name: kanboard
    image: "kanboard/kanboard:latest"

    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      DB_HOST: "mariadb:3306"
      DB_USER: root
      DB_PASS: password321
      DB_DATABASE: kanboardapp
      VIRTUAL_HOST: "kanboard.{{ user.domain }}"
      VIRTUAL_PORT: 443
      VIRTUAL_PROTO: https
      LETSENCRYPT_HOST: "kanboard.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
      PLUGIN_INSTALLER: "true"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/kanboard/data:/var/www/app/data"
      - "/opt/kanboard/plugins:/var/www/app/plugins"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - kanboard
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
