---
version: "2"
services:
  unifi-controller:
    image: linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - path to data:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    restart: unless-stopped


    Alternatively to manually adopt a device take these steps:

    ssh ubnt@$AP-IP
    mca-cli
    set-inform http://$address:8080/inform



    brettm357/unifi
